// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYM1L2cE-0USxoxaXkf9A04DTXZUqP_bo',
    appId: '1:438531225005:web:27b7524da92b21af049d24',
    messagingSenderId: '438531225005',
    projectId: 'budget-tracker-1cbb3',
    authDomain: 'budget-tracker-1cbb3.firebaseapp.com',
    storageBucket: 'budget-tracker-1cbb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyuaGseYgiGZSsp7ayRF64XFMe4Qa9tfc',
    appId: '1:438531225005:android:2fdc768dde7028d6049d24',
    messagingSenderId: '438531225005',
    projectId: 'budget-tracker-1cbb3',
    storageBucket: 'budget-tracker-1cbb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXuJZnCw_O5JIbALPKZ0E-WPCsTGYI17A',
    appId: '1:438531225005:ios:baed49f533cb0d59049d24',
    messagingSenderId: '438531225005',
    projectId: 'budget-tracker-1cbb3',
    storageBucket: 'budget-tracker-1cbb3.appspot.com',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXuJZnCw_O5JIbALPKZ0E-WPCsTGYI17A',
    appId: '1:438531225005:ios:c491462013d21919049d24',
    messagingSenderId: '438531225005',
    projectId: 'budget-tracker-1cbb3',
    storageBucket: 'budget-tracker-1cbb3.appspot.com',
    iosBundleId: 'com.example.budgetTracker.RunnerTests',
  );
}
